"""new  migration

Revision ID: 39c3c6bf53d6
Revises: 
Create Date: 2025-10-06 17:18:22.661866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39c3c6bf53d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('employee_id'))
        batch_op.drop_column('employee_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('employee_id', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_index(batch_op.f('employee_id'), ['employee_id'], unique=True)

    # ### end Alembic commands ###
