"""Add faculty_id to lecturers

Revision ID: c40174c9a2e5
Revises: da9880f4fe01
Create Date: 2025-10-07 22:05:27.923287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c40174c9a2e5'
down_revision = 'da9880f4fe01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_marks', sa.Integer(), nullable=True))

    with op.batch_alter_table('lecturer_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=False))
        batch_op.alter_column('department_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('department_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('lecturer_assignments', schema=None) as batch_op:
        batch_op.drop_column('visible')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_column('attendance_marks')

    # ### end Alembic commands ###
