"""close

Revision ID: dd02d01fa149
Revises: 39c3c6bf53d6
Create Date: 2025-10-06 22:31:34.642072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd02d01fa149'
down_revision = '39c3c6bf53d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lecturer_assignments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lecturers', ['lecturer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lecturer_assignments_ibfk_1'), 'users', ['lecturer_id'], ['id'])

    # ### end Alembic commands ###
